### ISSUE TITLE
咨询

### ISSUE THREAD

**Issue by guoyanb** [zhao62/Adaptively-Parametric-ReLU#1]
你好，自适应的APReLU是非常有意义的工作。近期 我尝试将思想用到自己的任务中。当用keras版的代码，调试的时候，遇到这样的问题“scales和neg_input两者的维度不一致因此就报错啦，multiply的规则是(计算输入张量列表的（逐元素间的）乘积。它接受一个张量的列表， 所有的张量必须有相同的输入尺寸， 然后返回一个张量（和输入张量尺寸相同）) ” neg_part = keras.layers.multiply([scales, neg_input])。可以告诉下 你在实验过程中 是如何将 scales的尺寸转换成和neg_input 一样？ 非常感谢

**Comment by zhao62** [comment]
我印象中Keras是支持broadcasting的，就是自动匹配维度，但是刚才搜了一下，发现不能自动broadcasting了，也不知道为什么。可能是Keras版本升级的时候，他们没顾及到这一点。

TensorFlow的multiply是支持自动broadcasting的，“If x.shape is not thes same as y.shape, they will be broadcast to a compatible shape.”（https://www.tensorflow.org/api_docs/python/tf/math/multiply ）。

我也只能建议用TensorFlow编写这一部分。

ps. 我觉得Keras本身就编写得不好，建议用TensorFlow、TFLearn，或者转向PyTorch。

**Comment by guoyanb** [comment]
谢谢解答

> 我印象中Keras是支持broadcasting的，就是自动匹配维度，但是刚才搜了一下，发现不能自动broadcasting了，也不知道为什么。可能是Keras版本升级的时候，他们没顾及到这一点。
> 
> TensorFlow的multiply是支持自动broadcasting的，“If x.shape is not thes same as y.shape, they will be broadcast to a compatible shape.”（https://www.tensorflow.org/api_docs/python/tf/math/multiply ）。
> 
> 我也只能建议用TensorFlow编写这一部分。
> 
> ps. 我觉得Keras本身就编写得不好，建议用TensorFlow、TFLearn，或者转向PyTorch。
