### ISSUE TITLE
关于如何加载振动信号

### ISSUE THREAD

**Issue by BALDman66** [zhao62/Adaptively-Parametric-ReLU#2]

**Comment by BALDman66** [comment]
作者您好 我看到你只提供了用于图像分类的代码  我最近也想研究关于振动信号的检测 如果您方便是否可以提供振动信号版的代码呢？

**Comment by BALDman66** [comment]
z15594674191@qq.com 这是我的邮箱如果您习惯使用邮箱的话

**Comment by BALDman66** [comment]
z15594674191@163.com这是我的邮箱如果您习惯使用邮箱的话

**Comment by zhao62** [comment]
您好，代码已发至邮箱，感谢您对这篇论文的兴趣
